//------------------------------------------------------------------------------
// <auto-generated>
// This code was automatically generated by the Domenici.Utilities.Configuration tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Domenici.Utilities.Configuration;

namespace SampleApplication.domenici.settings
{
    public static class Sample
    {
        public static partial class ItemSamples
        {
            public static string StringValue { get { return (string)SettingsManager.GetValue("ItemSamples/StringValue", typeof(string)); } }
        }
        public static partial class ItemSamples
        {
            public static int IntegerValue { get { return (int)SettingsManager.GetValue("ItemSamples/IntegerValue", typeof(int)); } }
        }
        public static partial class ItemSamples
        {
            public static decimal DecimalValue { get { return (decimal)SettingsManager.GetValue("ItemSamples/DecimalValue", typeof(decimal)); } }
        }
        public static partial class ItemSamples
        {
            public static bool BooleanValue { get { return (bool)SettingsManager.GetValue("ItemSamples/BooleanValue", typeof(bool)); } }
        }
    }
}
