title: Domenici.utilities.configuration
description: Strongly-typed configuration settings for .NET projects
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
