//------------------------------------------------------------------------------
// <auto-generated>
//     This code was automatically generated by the 2C2P configuration tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2C2P.Utilities.Configuration
{
    public static class AppSettingsManager
    {
        public static string testSetting { get { return SettingsManager.GetValue("testSetting"); } }
        public static string aaa { get { return SettingsManager.GetValue("aaa"); } }
        public static partial class section1
        {
            public static string key1_1 { get { return SettingsManager.GetValue("key1.1"); } }
        }
        public static partial class section1
        {
            public static partial class section1
            {
                public static string key1_1 { get { return SettingsManager.GetValue("key1.1"); } }
            }
        }
        public static partial class section1
        {
            public static partial class section1
            {
                public static partial class section1
                {
                    public static string key1_1 { get { return SettingsManager.GetValue("key1.1"); } }
                }
            }
        }
    }
}
